### ISSUE TITLE
Derive Eq, Ord, PartialEq and PartialOrd on EnumMap<K,V> when K and V impl those traits

### ISSUE THREAD

**Issue by klauria-factorial** [xfix/enum-map#28]
This would be broadly useful when using EnumMap<K,V> inside other structs where it's nice to be able to compare by value. If you think this would be good to add, I'm happy to take a shot, especially if you have some thoughts/opinions on how you think it should be done!

Thank you!

**Comment by xfix** [comment]
`EnumMap` already implements `Eq` and `PartialEq`.

As for `Ord`, the issue is mostly it's not clear how it should be implemented and currently I didn't want to decide on any particular implementation.

**Comment by klauria-factorial** [comment]
If V implements Ord, I would naively think that a fixed-length array of V's can implement Ord by lexicographic comparison of elements. Would that have some downside I'm not thinking of?
