### ISSUE TITLE
Derive Copy for EnumMap

### ISSUE THREAD

**Issue by gyscos** [xfix/enum-map#3]
Since it is really an array, which itself probably implements Copy.

**Comment by xfix** [comment]
It is already derived with `impl<K: Internal<V>, V> Copy for EnumMap<K, V> where K::Array: Copy {}`. The reason why the manual implementation is here is that it otherwise would put a pointless bound on `K` which isn't necessary.

**Comment by xfix** [comment]
That said, that made me realize that `EnumMap` of an option was not copyable, as it wasn't implemented as an array.
