### ISSUE TITLE
enum_map! is unusable as a const initializer, and the array field being private makes manual initialization impossible too

### ISSUE THREAD

**Issue by bill-myers** [xfix/enum-map#5]
enum_map! is probably not fixable in stable Rust without the unstable const fn support, unless there's some clever approach I'm not seeing.

However, making the field public would allow to manually do it.

There's also the possibility of writing an enum_with_map! macro that would create both an enum and an enum map const (by just writing both the variants and the array items in the same order as provided by the user), which is easy and might be good enough in practice.

Possible implementation of such a macro (after changing EnumMap to be a tuple struct with a public array field):
```
#[macro_export]
macro_rules! enum_with_map {
	{$(#[$m:meta])* enum $e:ident, const $n:ident : EnumMap<_, $d:ty> = {$($k:ident => $v:expr),*};} => {
        $(#[$m])* #[derive(EnumMap)] enum $e {
            $($k),*
        }

        const $n: EnumMap<$e, $d> = EnumMap([
            $($v),*
        ]);
    };
}
```

**Comment by xfix** [comment]
Yeah, understandably an issue, but Rust doesn't really provide a way to deal with it. I would either need to use procedural macros (nightly only as of now) or const functions (which aren't usable enough even on nightly, but there is possibility that it will soon be with miri having been recently merged into Rust compiler). [Procedural macro hack](https://github.com/dtolnay/proc-macro-hack) is pretty much unusable here after [recent changes to hygiene of `macro_rules!`](https://github.com/rust-lang/rust/issues/46478).

As a workaround, [`lazy_static` crate](https://crates.io/crates/lazy_static) could be used. This will be looked on later once `const fn` becomes usable enough.
