### ISSUE TITLE
`from_usize` gives a generic, misleading panic message on out-of-bounds

### ISSUE THREAD

**Issue by cbiffle** [xfix/enum-map#51]
Currently, the implementation of `from_usize` for `derive(Enum)` will panic if given an out-of-bounds integer. That seems fine.

However, the panic message is currently:

```
panicked at 'internal error: entered unreachable code'
```

To me, that suggests an internal logic error in the derived impl, which doesn't appear to be the case. This case is _trivially_ reachable if the caller provides a bogus integer. `unreachable` is an unusual way of handling this; for instance, slice index out of bounds does not print `unreachable` but rather that a slice index was out of bounds.

As a user I think it'd be a better experience if the message were something like `index out of range for Enum::from_usize`.

**Comment by xfix** [comment]
Makes sense to me.

Historically, `Enum` trait methods were an undocumented implementation detail, but now that it is actually documented I probably should change the error message.
